### ISSUE TITLE
Incorrect Handling of `case when ... end`

### ISSUE THREAD

**Issue by posgarou** [camertron/scuttle-rb#2]
First off, thanks for your work on this amazing tool.

I've noticed that Scuttle doesn't seem to handle `CASE WHEN ... END` statements properly.  Consider the following simplified query (working with postgres):

```sql
SELECT game_events.name, sum(CASE WHEN game_events.has_happened THEN 1 ELSE 0 END) total_has_happened
FROM game_events
GROUP BY game_events.name;
```

This generates the following incorrect Arel mapping:

```ruby
GameEvent.select(
  [
    GameEvent.arel_table[:name], Arel::Nodes::NamedFunction.new('sum', [0]).as('total_has_happened')
  ]
).group(GameEvent.arel_table[:name])
```

Since to my knowledge case statements aren't directly supported in Arel (https://github.com/rails/arel/issues/168), it would be helpful if the above instead treated `CASE ... END` as raw sql.

```ruby
GameEvent.select(
  [
    GameEvent.arel_table[:name], Arel.sql('CASE WHEN game_events.has_happened THEN 1 ELSE 0 END').sum.as('total_has_happened')
  ]
).group(GameEvent.arel_table[:name])
```

**Comment by camertron** [comment]
Thanks for the bug report, @posgarou. The fact that Arel doesn't support CASE statements directly is a bit of a shame, since it appears the WHEN parts can be full SQL expressions. I think your solution of embedding the raw CASE string is probably the only thing we can do for now. Any interest in submitting a PR for this?

**Comment by posgarou** [comment]
@camertron Sure, I'll give it a shot.  I'll try to submit a PR within a week or so.  Thanks!

**Comment by posgarou** [comment]
@camertron Looked into this more tonight, and I'm going to have to bow out on the PR. I didn't realize the change would have to be made in [scuttle-java](https://github.com/camertron/scuttle-java)—haven't worked in Java in forever.  Sorry!

**Comment by camertron** [comment]
Alright, that's no problem @posgarou. I'll take a look at it.

**Comment by camertron** [comment]
Fix deployed.
